# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: monexec
    main: cmd/monexec/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm64
archive:
  format: tar.gz
nfpm:
  homepage: https://github.com/reddec/monexec
  description: Tool for controlling processes like a supervisord but with some features
  maintainer: RedDec <owner@reddec.net>
  license: MIT
  formats:
    - deb
